// Code generated by table/gen.go. DO NOT EDIT.

package ec2

import (
	"sort"

	"github.com/nekrassov01/aws-describer/internal/api/ec2"
	"github.com/nekrassov01/aws-describer/internal/tab"
)

func PrintSubnetRouteInfo(info []ec2.SubnetRouteInfo, output string, header bool, mergeFields, ignoreFields []int) error {
	sort.SliceStable(info, func(i, j int) bool {
		if info[i].Region != info[j].Region {
			return info[i].Region < info[j].Region
		}
		if info[i].SubnetName != info[j].SubnetName {
			return info[i].SubnetName < info[j].SubnetName
		}
		if info[i].AvailabilityZone != info[j].AvailabilityZone {
			return info[i].AvailabilityZone < info[j].AvailabilityZone
		}
		if info[i].VpcName != info[j].VpcName {
			return info[i].VpcName < info[j].VpcName
		}
		if info[i].RouteTableName != info[j].RouteTableName {
			return info[i].RouteTableName < info[j].RouteTableName
		}
		if info[i].DestinationType != info[j].DestinationType {
			return info[i].DestinationType < info[j].DestinationType
		}
		return info[i].TargetType < info[j].TargetType
	})
	if len(mergeFields) == 0 {
		mergeFields = []int{0, 1, 2, 3, 4, 5, 6}
	}
	if err := tab.PrintTable(info, output, header, mergeFields, ignoreFields); err != nil {
		return err
	}
	return nil
}
