// Code generated by table/gen.go. DO NOT EDIT.

package ec2

import (
	"sort"

	"github.com/nekrassov01/aws-describer/internal/api/ec2"
	"github.com/nekrassov01/aws-describer/internal/tab"
)

func PrintVpcAttributeInfo(info []ec2.VpcAttributeInfo, output string, header bool, mergeFields, ignoreFields []int) error {
	sort.SliceStable(info, func(i, j int) bool {
		if info[i].Region != info[j].Region {
			return info[i].Region < info[j].Region
		}
		if info[i].VpcName != info[j].VpcName {
			return info[i].VpcName < info[j].VpcName
		}
		if info[i].DhcpOptionsName != info[j].DhcpOptionsName {
			return info[i].DhcpOptionsName < info[j].DhcpOptionsName
		}
		if info[i].OwnerId != info[j].OwnerId {
			return info[i].OwnerId < info[j].OwnerId
		}
		if info[i].IsDefault != info[j].IsDefault {
			return info[i].IsDefault
		}
		return info[i].InstanceTenancy < info[j].InstanceTenancy
	})
	if err := tab.PrintTable(info, output, header, mergeFields, ignoreFields); err != nil {
		return err
	}
	return nil
}
