// Code generated by table/gen.go. DO NOT EDIT.

package ec2

import (
	"sort"

	"github.com/nekrassov01/aws-describer/internal/api/ec2"
	"github.com/nekrassov01/aws-describer/internal/tab"
)

func PrintInstanceStorageInfo(info []ec2.InstanceStorageInfo, output string, header bool, mergeFields, ignoreFields []int) error {
	sort.SliceStable(info, func(i, j int) bool {
		if info[i].AvailabilityZone != info[j].AvailabilityZone {
			return info[i].AvailabilityZone < info[j].AvailabilityZone
		}
		if info[i].InstanceName != info[j].InstanceName {
			return info[i].InstanceName < info[j].InstanceName
		}
		if info[i].DeviceName != info[j].DeviceName {
			return info[i].DeviceName < info[j].DeviceName
		}
		if info[i].VolumeName != info[j].VolumeName {
			return info[i].VolumeName < info[j].VolumeName
		}
		if info[i].VolumeType != info[j].VolumeType {
			return info[i].VolumeType < info[j].VolumeType
		}
		if info[i].VolumeSize != info[j].VolumeSize {
			return info[i].VolumeSize < info[j].VolumeSize
		}
		return info[i].IOPS < info[j].IOPS
	})
	if len(mergeFields) == 0 {
		mergeFields = []int{0, 1, 2, 3, 4}
	}
	if err := tab.PrintTable(info, output, header, mergeFields, ignoreFields); err != nil {
		return err
	}
	return nil
}
