// Code generated by table/gen.go. DO NOT EDIT.

package ec2

import (
	"sort"

	"github.com/nekrassov01/aws-describer/internal/api/ec2"
	"github.com/nekrassov01/aws-describer/internal/tab"
)

func PrintRouteTableAssociationInfo(info []ec2.RouteTableAssociationInfo, output string, header bool, mergeFields, ignoreFields []int) error {
	sort.SliceStable(info, func(i, j int) bool {
		if info[i].Region != info[j].Region {
			return info[i].Region < info[j].Region
		}
		if info[i].RouteTableName != info[j].RouteTableName {
			return info[i].RouteTableName < info[j].RouteTableName
		}
		if info[i].VpcName != info[j].VpcName {
			return info[i].VpcName < info[j].VpcName
		}
		if info[i].Main != info[j].Main {
			return info[j].Main
		}
		if info[i].SubnetName != info[j].SubnetName {
			return info[i].SubnetName < info[j].SubnetName
		}
		return info[i].State < info[j].State
	})
	if len(mergeFields) == 0 {
		mergeFields = []int{0, 1, 2, 3}
	}
	if err := tab.PrintTable(info, output, header, mergeFields, ignoreFields); err != nil {
		return err
	}
	return nil
}
