// Code generated by table/gen.go. DO NOT EDIT.

package ec2

import (
	"sort"

	"github.com/nekrassov01/aws-describer/internal/api/ec2"
	"github.com/nekrassov01/aws-describer/internal/tab"
)

func PrintRouteTableInfo(info []ec2.RouteTableInfo, output string, header bool, mergeFields, ignoreFields []int) error {
	sort.SliceStable(info, func(i, j int) bool {
		if info[i].Region != info[j].Region {
			return info[i].Region < info[j].Region
		}
		if info[i].RouteTableName != info[j].RouteTableName {
			return info[i].RouteTableName < info[j].RouteTableName
		}
		if info[i].DestinationType != info[j].DestinationType {
			return info[i].DestinationType < info[j].DestinationType
		}
		if info[i].VpcName != info[j].VpcName {
			return info[i].VpcName < info[j].VpcName
		}
		if info[i].Destination != info[j].Destination {
			return info[i].Destination < info[j].Destination
		}
		if info[i].TargetType != info[j].TargetType {
			return info[i].TargetType < info[j].TargetType
		}
		if info[i].Target != info[j].Target {
			return info[i].Target < info[j].Target
		}
		return info[i].State < info[j].State
	})
	if len(mergeFields) == 0 {
		mergeFields = []int{0, 1, 2, 3}
	}
	if err := tab.PrintTable(info, output, header, mergeFields, ignoreFields); err != nil {
		return err
	}
	return nil
}
