// Code generated by describer/ec2_gen.go. DO NOT EDIT.

package describer

import (
	ec2api "github.com/nekrassov01/aws-describer/internal/api/ec2"
	ec2tab "github.com/nekrassov01/aws-describer/internal/tab/ec2"
	"github.com/urfave/cli/v2"
)

func (a *app) doSecurityGroupPermissionsInfo(c *cli.Context) error {
	filters, err := ec2api.ParseEc2Filters(a.dest.ec2Filter)
	if err != nil {
		return err
	}
	info, err := ec2api.DescribeSecurityGroupPermissionsInfo(c.Context, a.config, a.flag.regions.GetDestination(), a.flag.ids.GetDestination(), a.flag.names.GetDestination(), filters, a.dest.ec2DefaultFilter)
	if err != nil {
		return err
	}
	if err := ec2tab.PrintSecurityGroupPermissionsInfo(info, a.dest.output, a.dest.header, a.flag.merge.GetDestination(), a.flag.ignore.GetDestination()); err != nil {
		return err
	}
	return nil
}
